cc_test(
    name = "ipc_sender_tests",
    srcs = [
        "ipc_sender_test.cpp"
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ]
)

cc_test(
    name = "ipc_receiver_tests",
    srcs = [
        "ipc_receiver_test.cpp",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ]
)